### ISSUE TITLE
scala 2.13

### ISSUE THREAD

**Issue by TimPigden** [typelevel/squants#344]
Hi, any chance of a 2.13 build please?

**Comment by cquiroz** [comment]
Unfortunately there is an oustanding bug to compile on 2.13 that may take a while to fix

**Comment by ybasket** [comment]
@cquiroz any update on the outstanding bug?

If there's no fix yet, maybe you can give a hint or two about what's the problem or open a WIP PR, so that others can try to help there? I'd gladly invest some time to make squants 2.13 ready if I can.

**Comment by cquiroz** [comment]
We are hitting this bug
https://github.com/scala/bug/issues/11640

**Comment by ybasket** [comment]
The scalac bug was closed today, but it seems as it didn't solve the problem for squants, there's still a cyclic reference error when building against the scalac snapshot `2.13.1-bin-dfde51f` which is supposed to have it fixed (at least if I got the system of snapshot versions right).

Branch to test can be found here: https://github.com/ybasket/squants/tree/scala-2.13

Guess we should try to extract a minimal example of the compilation error and open a new scalac issue…not sure I will soon have the time to do that.

**Comment by cquiroz** [comment]
This is the error in question but I haven't been able to minimize it
```
/Users/cquiroz/Projects/squants/shared/src/main/scala/squants/motion/Acceleration.scala:25:25: illegal cyclic reference involving class Velocity [error] with TimeDerivative[Velocity]
```
